const id = "Tackling Long Form Questions.mdx";
						const collection = "blog";
						const slug = "tackling-long-form-questions";
						const body = "\nThis section of every question paper carries the most marks. The material discussed in this newsletter\napplies mostly to literature and non-computation subjects, but these principles can be adopted for math\nintense subjects as well.\n<small>\"The only true wisdom is in knowing you know nothing.\" — Socrates</small> <br/>\n1. __Read the question carefully.__\n    + Read the question carefully and thoroughly.\n    + Understand what is being asked of you.\n    + Highlight any important keywords or specific instructions.\n2. __Plan your response.__\n    <ul><li> Structure your response before you decide to write down your final answer.</li></ul>\n3. __Create an introduction.__\n    + Begin your answer with a clear introduction that states the purpose of your answer.\n    + Often the opening sets the tone and a good one makes it easier to write down whatever\n    follows.\n4. __Organize your ideas before writing your final answer.__\n    + Structure your answer logically with clear sections (beginning, middle, and end)\n    + Use headings to separate your response into smaller manageable ideas, each section\n    must tackle one idea.\n5. __Answer the question, provide any additional evidence if required.__\n    + Use other ideas in the subject that are related to what you are trying to answer to\n    strengthen your arguments.\n    + Make sure you answer the questions fully, do not omit anything you think is necessary to\n    earn you more marks.\n6. __Stay on topic.__\n    + Stick to the topic.\n    + The last thing you want to do is waste your time writing an off-topic answer that will not\n    earn you marks (in university you can lose marks for this)\n    + This can be avoided by ensuring that you understand the question.\n7. __Edit and proofread your work.__\n    + Double-check your work after writing.\n8. __Manage your time.__\n    + Ration your time accordingly. At the start of the test, take note of how much each\n    question is worth and allocate more time to questions that weigh more.\n    + Learn how to write faster with a clear handwriting to minimize the amount of time you\nuse.\n9. __Stay calm and positive.__\n    + If you are running out of time, the best thing to do is to remain calm and keep doing\n    your best. You might not be able to finish on time, but you can make sure that whatever\n    you wrote is correct and will get you the distinction you need.\n\n<br></br>\n\n<small>“If you know what you are doing then, it shouldn’t take you too long to do it” – W.P.A.</small> <br/>\n<small>\"The direction in which education starts a man, will determine his future in\nlife.\" — Plato </small>";
						const data = {title:"Tackling Long Form Questions",description:"learn how to navigate answering test questions that require lengthy answers.",pubDate:new Date(1705788000000),heroImage:"/blog-placeholder-2.jpg",imageAlt:"Color image",tags:["Test and exam","Study","Learning"],link:"/blog/tackling-long-form-questions/",category:"Study"};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Lapane/Documents/Code/Astro/WPA_Blog/Wolfie/src/content/blog/Tackling Long Form Questions.mdx",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
